# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

variables:
  buildConfiguration: 'Release'
  location: 'eastus'
  acrHostName: 'knoxdocker001.azurecr.io'
  acrName: 'knoxdocker001acr'
  rgName: 'knoxdocker001-rg'
  containerName: 'knoxdocker001'
  appName: 'knoxdocker001'
  vmImageName: 'ubuntu-latest'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

resources:
- repo: self



stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      image: '$(vmImageName)'
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Create Azure Container Registry'
      inputs:
        azureSubscription: 'azureSrvcConn'
        resourceGroupName: '$(rgName)'
        location: $(location)
        csmFile: '$(System.DefaultWorkingDirectory)/**/acr-temp-new.json'
        overrideParameters: '-acrName "$(acrName)" -acrSku standard'
    - task: Docker@1
      displayName: 'Build container image'
      inputs:
        azureSubscriptionEndpoint: 'azureSrvcConn'
        azureContainerRegistry: '$(acrHostName)'
        imageName: '$(imageName):$(Build.BuildId)'
        useDefaultContext: false
        buildContext: '$(System.DefaultWorkingDirectory)/PublishedWebApp'
  
      # Push container image
    - task: Docker@1
      displayName: 'Push container image'
      inputs:
        azureSubscriptionEndpoint: 'azureSrvcConn'
        azureContainerRegistry: '$(acrHostName)'
        command: 'Push an image'
        imageName: '$(imageName):$(Build.BuildId)'
